// Deterministic, dependency-free classic-script bundle. The shipped JSON is the master.
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';
import './scripts/validate-data.mjs';
const read = name => readFile(new URL(name, import.meta.url), 'utf8');
const [core, clipboard, ui, styles, decorations, categories] = await Promise.all([
  read('reference/core.mjs'), read('reference/clipboard.mjs'), read('ui.js'),
  read('data/styles.json'), read('data/decorations.json'), read('data/categories.json')
]);
const data = {styles: JSON.parse(styles), decorations: JSON.parse(decorations), categories: JSON.parse(categories)};
const exports = [...(core + clipboard).matchAll(/export (?:async )?(?:function|const) (\w+)/g)].map(m => m[1]);
const bundle = `// Generated by features/decorative-text/build.mjs; edit source files, not this bundle.\n(function (root) {\n"use strict";\n${(core + clipboard).replace(/\bexport /g, '')}\nconst data = ${JSON.stringify(data)};\nconst domain = {${exports.join(', ')}};\nroot.TextTools = root.TextTools || {};\nroot.TextTools.decorativeDomain = { ...domain, data };\n${ui}\n}(window));\n`;
export async function buildDecoration(jsPath, cssPath) {
  await writeFile(jsPath, bundle);
  // CSS is kept in the existing stylesheet so file:// and the strict CSP still work.
  const css = await readFile(cssPath, 'utf8');
  const marker = '/* BEGIN DECORATIVE TEXT ADDON */';
  const base = css.split(marker)[0].trimEnd();
  await writeFile(cssPath, base + '\n\n' + marker + '\n' + await read('style.css'));
  console.log(`Decorative bundle: ${Buffer.byteLength(bundle)} bytes; gzip ${gzipSync(bundle).length} bytes`);
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await buildDecoration(resolve(process.argv[2] || 'js/decorative.js'), resolve(process.argv[3] || 'css/style.css'));
}
